//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc2SuchTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Breakdowns
    {
        public int BreakDownID { get; set; }
        public string TruckNumberPlate { get; set; }
        public string BreakdownDescription { get; set; }
        public string BreakdownLocation { get; set; }
    }
}
