//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc2SuchTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public int CargoID { get; set; }
        public string PickUpArea { get; set; }
        public Nullable<decimal> C6m { get; set; }
        public Nullable<decimal> C12m { get; set; }
    }
}
