//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc2SuchTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobQueue
    {
        public int queueId { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> PriorityScore { get; set; }
        public string QueueStatus { get; set; }
    
        public virtual Deliveryjob Deliveryjob { get; set; }
    }
}
