//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc2SuchTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int QuoteID { get; set; }
        public string PickUpArea { get; set; }
        public string DropOffArea { get; set; }
        public Nullable<int> CargoSize { get; set; }
        public Nullable<decimal> CargoWeight { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string ReferenceKey { get; set; }
    }
}
